import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import SelfImg from "@/../public/self.jpg";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="w-screen h-screen flex gap-5 bg-gray-200 p-8" >
          <div className="w-[480px] h-full rounded-2xl bg-white flex 
          justify-start items-center flex-col p-[30px] pt-[80px] overflow-y-auto overflow-x-hidden">
            <Image src={SelfImg} alt="self profile" className="w-[80px] h-[80px] rounded-full "  />
            <h1 className="mt-2">Motish</h1>

            <p className="max-w-[380px] text-center">個人簡介</p>

            {/* SocailLinks */}
            <div className="flex gap-2 my-5">

              <a href="https://www.instagram.com/motish9527/" target="_blank" > 
                <div className=" bg-gray-300 w-[40px] h-[40px] rounded-full"></div>
              </a>
              <a href="https://www.instagram.com/motish9527/" target="_blank" > 
                <div className=" bg-gray-300 w-[40px] h-[40px] rounded-full"></div>
              </a>
              <a href="https://www.instagram.com/motish9527/" target="_blank" > 
                <div className=" bg-gray-300 w-[40px] h-[40px] rounded-full"></div>
              </a> 
              <a href="https://www.instagram.com/motish9527/" target="_blank" > 
                <div className=" bg-gray-300 w-[40px] h-[40px] rounded-full"></div>
              </a>

            </div>

            {/* 作品集 */}
            <div className="w-full flex flex-col gap-2">
              <div className="w-full h-[84px] bg-gray-300 rounded-xl">睡太久了......</div>
              <div className="w-full h-[84px] bg-gray-300 rounded-xl">好想回家</div>
              <div className="w-full h-[84px] bg-gray-300 rounded-xl">學經二</div>
              <div className="w-full h-[84px]  bg-red-700 rounded-xl">學經三</div>


            </div>

          
          
          
          </div>
          
          {children}
      
        </div>
      
      </body>
    </html>
  );
}
